[package]
name="c_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
regex = "1.11.1"
unicode-segmentation = "1.12.0"
anyhow = "1.0.98"
log = "0.4.27"
env_logger = "0.11.8"
